//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int WorkerID { get; set; }
        public string Name { get; set; }
        public string Place { get; set; }
        public int DepartmentDepartmentNo { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
